# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Block.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
import sys
if sys.version_info >= (3,):
  #some constants that are python2 only
  unicode = str
  long = int
  range = range
  unichr = chr
  def b(s):
    return s.encode("latin-1")
  def u(s):
    return s
else:
  #some constants that are python2 only
  range = xrange
  unicode = unicode
  long = long
  unichr = unichr
  def b(s):
    return s
  # Workaround for standalone backslash
  def u(s):
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")

from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


try:
    from . import Tile_pb2
except ImportError: 
    import Tile_pb2
try:
    from . import Plant_pb2
except ImportError: 
    import Plant_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Block.proto',
  package='dfproto',
  serialized_pb=b('\n\x0b\x42lock.proto\x12\x07\x64\x66proto\x1a\nTile.proto\x1a\x0bPlant.proto\"d\n\x05\x42lock\x12\t\n\x01x\x18\x01 \x02(\r\x12\t\n\x01y\x18\x02 \x02(\r\x12\t\n\x01z\x18\x03 \x02(\r\x12\x1b\n\x04tile\x18\x04 \x03(\x0b\x32\r.dfproto.Tile\x12\x1d\n\x05plant\x18\x05 \x03(\x0b\x32\x0e.dfproto.PlantB\x02H\x03'))




_BLOCK = _descriptor.Descriptor(
  name='Block',
  full_name='dfproto.Block',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='dfproto.Block.x', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y', full_name='dfproto.Block.y', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z', full_name='dfproto.Block.z', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tile', full_name='dfproto.Block.tile', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='plant', full_name='dfproto.Block.plant', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=49,
  serialized_end=149,
)

_BLOCK.fields_by_name['tile'].message_type = Tile_pb2._TILE
_BLOCK.fields_by_name['plant'].message_type = Plant_pb2._PLANT
DESCRIPTOR.message_types_by_name['Block'] = _BLOCK

Block = _reflection.GeneratedProtocolMessageType('Block', (_message.Message,),
    {
      'DESCRIPTOR': _BLOCK,
      # @@protoc_insertion_point(class_scope:dfproto.Block)
    })


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), b('H\003'))
# @@protoc_insertion_point(module_scope)
