# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Map.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
import sys
if sys.version_info >= (3,):
  #some constants that are python2 only
  unicode = str
  long = int
  range = range
  unichr = chr
  def b(s):
    return s.encode("latin-1")
  def u(s):
    return s
else:
  #some constants that are python2 only
  range = xrange
  unicode = unicode
  long = long
  unichr = unichr
  def b(s):
    return s
  # Workaround for standalone backslash
  def u(s):
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")

from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)


try:
    from . import Material_pb2
except ImportError: 
    import Material_pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Map.proto',
  package='dfproto',
  serialized_pb=b('\n\tMap.proto\x12\x07\x64\x66proto\x1a\x0eMaterial.proto\"\x91\x01\n\x03Map\x12\x0e\n\x06x_size\x18\x01 \x02(\r\x12\x0e\n\x06y_size\x18\x02 \x02(\r\x12\x0e\n\x06z_size\x18\x03 \x02(\r\x12-\n\x12inorganic_material\x18\x04 \x03(\x0b\x32\x11.dfproto.Material\x12+\n\x10organic_material\x18\x05 \x03(\x0b\x32\x11.dfproto.MaterialB\x02H\x03'))




_MAP = _descriptor.Descriptor(
  name='Map',
  full_name='dfproto.Map',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x_size', full_name='dfproto.Map.x_size', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='y_size', full_name='dfproto.Map.y_size', index=1,
      number=2, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='z_size', full_name='dfproto.Map.z_size', index=2,
      number=3, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='inorganic_material', full_name='dfproto.Map.inorganic_material', index=3,
      number=4, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='organic_material', full_name='dfproto.Map.organic_material', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=39,
  serialized_end=184,
)

_MAP.fields_by_name['inorganic_material'].message_type = Material_pb2._MATERIAL
_MAP.fields_by_name['organic_material'].message_type = Material_pb2._MATERIAL
DESCRIPTOR.message_types_by_name['Map'] = _MAP

Map = _reflection.GeneratedProtocolMessageType('Map', (_message.Message,),
    {
      'DESCRIPTOR': _MAP,
      # @@protoc_insertion_point(class_scope:dfproto.Map)
    })


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), b('H\003'))
# @@protoc_insertion_point(module_scope)
