# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Material.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
import sys
if sys.version_info >= (3,):
  #some constants that are python2 only
  unicode = str
  long = int
  range = range
  unichr = chr
  def b(s):
    return s.encode("latin-1")
  def u(s):
    return s
else:
  #some constants that are python2 only
  range = xrange
  unicode = unicode
  long = long
  unichr = unichr
  def b(s):
    return s
  # Workaround for standalone backslash
  def u(s):
    return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")

from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Material.proto',
  package='dfproto',
  serialized_pb=b('\n\x0eMaterial.proto\x12\x07\x64\x66proto\"\'\n\x08Material\x12\r\n\x05index\x18\x01 \x02(\r\x12\x0c\n\x04name\x18\x02 \x02(\tB\x02H\x03'))




_MATERIAL = _descriptor.Descriptor(
  name='Material',
  full_name='dfproto.Material',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='index', full_name='dfproto.Material.index', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='name', full_name='dfproto.Material.name', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode(b(""), "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=27,
  serialized_end=66,
)

DESCRIPTOR.message_types_by_name['Material'] = _MATERIAL

Material = _reflection.GeneratedProtocolMessageType('Material', (_message.Message,),
    {
      'DESCRIPTOR': _MATERIAL,
      # @@protoc_insertion_point(class_scope:dfproto.Material)
    })


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), b('H\003'))
# @@protoc_insertion_point(module_scope)
